import Head from "next/head";
import { Hero, Main } from "@/sections";

const heroProps = {
  title: "Agency procurement, outsourced.",
  image: {
    large: { src: "/img/heroimg.png", alt: "", width: 1000, height: 1680 },
    small: {
      src: "/img/heroimg-small.png",
      alt: "",
      width: 1000,
      height: 1680,
    },
  },
  description: "Start the process here",
  ctaText: "Start",
};

const mainProps = {
  title: "Managed agency selection",
  description: "Strengthen your onboarding process",
  image: { src: "/img/video.png", alt: "", width: 1000, height: 1680 },
  content: [
    {
      id: 1,
      heading: "Brief",
      text: "Complete brief writing or simple guidance on what to include, we've got you covered.",
      image: { src: "/img/image-1.png", alt: "", width: 91, height: 91 },
      wordsToBold: "brief writing or simple guidance",
      link: { url: "https://goodbrief.io", target: "_blank" },
    },

    {
      id: 2,
      heading: "Search",
      text: "In-depth agency search covering; criteria matching, door knocking and due-diligence vetting.",
      image: { src: "/img/image-2.png", alt: "", width: 91, height: 91 },
      wordsToBold: "criteria matching",
    },

    {
      id: 3,
      heading: "Pitch",
      text: "Comprehensive pitch management, including comms, diary management and pitch hosting.",
      image: { src: "/img/image-3.png", alt: "", width: 91, height: 91 },
      wordsToBold: "pitch management",
    },
  ],
};

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJS Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero {...heroProps} />
        <Main {...mainProps} />
      </div>
    </>
  );
}
